name: Continuous integration

on:
  push:
    branches:
      - webtransport-wasm-ext-test2

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2 # Fail cache download after 2 minutes.

jobs:
  webtransport_tests:
    name: Test WebTransport
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transports/webtransport-websys
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: docker/setup-buildx-action@v2

        #- uses: nanasess/setup-chromedriver@v2
        #with:
        # chromedriver-version: '114.0.5735.90'

      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: wasm-pack@0.11.1

      - name: Build echo-server
        run: |
            pwd
            ls -la
            docker buildx build -o type=local,dest=echo-server -t echo-server echo-server

      - name: Run wasm-pack test (Chrome)
        run: |
          ./echo-server/echo-server &
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
          wasm-pack test --chrome --headless
